###############################################################################
# METIS DEVELOPMENT MAKEFILE
# Copyright (c) 2001-2007 Joe Hurd, distributed under the GNU GPL version 2
###############################################################################

.PRECIOUS: bin/mlton/%.sml bin/mlton/%.mlb

###############################################################################
# Cleaning temporary files.
###############################################################################

TEMPFILE = Makefile-temp-file

TEMP += $(TEMPFILE) \
        cnf_*.tptp saturation.tptp \
	bin/mlton/*.ssa bin/mlton/*.ssa2 \
        bin/mlton/benchmark \
        mlmon.out profile-*

###############################################################################
# The ML preprocessor.
###############################################################################

#MLPP_OPTS += -r 'MetisDebug'
#MLPP_OPTS += -r 'MetisDebug|MetisTrace[0-1]'
#MLPP_OPTS += -r 'MetisDebug|MetisTrace[0-2]'
#MLPP_OPTS += -r 'MetisDebug|MetisTrace[0-3]'
#MLPP_OPTS += -r 'MetisDebug|MetisTrace[0-4]'
#MLPP_OPTS += -r 'MetisDebug|MetisTrace[0-5]'
#MLPP_OPTS += -r 'MetisDebug|MetisTrace[0-6]'
#MLPP_OPTS += -r 'BasicDebug|MetisDebug'
#MLPP_OPTS += -r 'BasicDebug|MetisDebug|MetisTrace[0-9]'

###############################################################################
# The Moscow ML compiler.
###############################################################################

MOSML_DEP = scripts/mosml_dep

bin/mosml/Makefile.src: Makefile Makefile.dev $(MOSML_DEP) $(MLPP)
	@echo
	@echo '****************************************************'
	@echo '* Regenerating the Moscow ML makefile dependencies *'
	@echo '****************************************************'
	@echo
	@$(MOSML_DEP) $(MOSML_SRC) $(MOSML_TARGETS) > $@

###############################################################################
# The MLton compiler.
###############################################################################

MLTON_OPTS += -verbose 1 -keep ssa -keep ssa2
#MLTON_OPTS += -inline 100000
#MLTON_OPTS += -const 'MLton.safe false' -const 'MLton.detectOverflow false'
#MLTON_OPTS += -const 'Exn.keepHistory true'

###############################################################################
# Moving source files around.
###############################################################################

src/ElementSet.sig: ../basic/src/ElementSet.sig $(COPY) ; @$(COPY) $< $@
src/ElementSet.sml: ../basic/src/ElementSet.sml $(COPY) ; @$(COPY) $< $@
src/Heap.sig: ../basic/src/Heap.sig $(COPY) ; @$(COPY) $< $@
src/Heap.sml: ../basic/src/Heap.sml $(COPY) ; @$(COPY) $< $@
src/KeyMap.sig: ../basic/src/KeyMap.sig $(COPY) ; @$(COPY) $< $@
src/KeyMap.sml: ../basic/src/KeyMap.sml $(COPY) ; @$(COPY) $< $@
src/Lazy.sig: ../basic/src/Lazy.sig $(COPY) ; @$(COPY) $< $@
src/Lazy.sml: ../basic/src/Lazy.sml $(COPY) ; @$(COPY) $< $@
src/Map.sig: ../basic/src/Map.sig $(COPY) ; @$(COPY) $< $@
src/Map.sml: ../basic/src/Map.sml $(COPY) ; @$(COPY) $< $@
src/Options.sig: ../basic/src/Options.sig $(COPY) ; @$(COPY) $< $@
src/Options.sml: ../basic/src/Options.sml $(COPY) ; @$(COPY) $< $@
src/Ordered.sig: ../basic/src/Ordered.sig $(COPY) ; @$(COPY) $< $@
src/Ordered.sml: ../basic/src/Ordered.sml $(COPY) ; @$(COPY) $< $@
src/Parse.sig: ../basic/src/Parse.sig $(COPY) ; @$(COPY) $< $@
src/Parse.sml: ../basic/src/Parse.sml $(COPY) ; @$(COPY) $< $@
src/Portable.sig: ../basic/src/Portable.sig $(COPY) ; @$(COPY) $< $@
src/PortableMosml.sml: ../basic/src/PortableMosml.sml $(COPY) ; @$(COPY) $< $@
src/PortableMlton.sml: ../basic/src/PortableMlton.sml $(COPY) ; @$(COPY) $< $@
src/PortablePolyml.sml: ../basic/src/PortablePolyml.sml $(COPY) ; @$(COPY) $< $@
src/Print.sig: ../basic/src/Print.sig $(COPY) ; @$(COPY) $< $@
src/Print.sml: ../basic/src/Print.sml $(COPY) ; @$(COPY) $< $@
src/Random.sig: ../basic/src/Random.sig $(COPY) ; @$(COPY) $< $@
src/Random.sml: ../basic/src/Random.sml $(COPY) ; @$(COPY) $< $@
src/RandomMap.sml: ../basic/src/RandomMap.sml $(COPY) ; @$(COPY) $< $@
src/RandomSet.sml: ../basic/src/RandomSet.sml $(COPY) ; @$(COPY) $< $@
src/Set.sig: ../basic/src/Set.sig $(COPY) ; @$(COPY) $< $@
src/Set.sml: ../basic/src/Set.sml $(COPY) ; @$(COPY) $< $@
src/Sharing.sig: ../basic/src/Sharing.sig $(COPY) ; @$(COPY) $< $@
src/Sharing.sml: ../basic/src/Sharing.sml $(COPY) ; @$(COPY) $< $@
src/Stream.sig: ../basic/src/Stream.sig $(COPY) ; @$(COPY) $< $@
src/Stream.sml: ../basic/src/Stream.sml $(COPY) ; @$(COPY) $< $@
src/Useful.sig: ../basic/src/Useful.sig $(COPY) ; @$(COPY) $< $@
src/Useful.sml: ../basic/src/Useful.sml $(COPY) ; @$(COPY) $< $@

src/selftest.sml: test/test.sml $(COPY) ; @$(COPY) $< $@

src/benchmark.sml: src/metis.sml $(COPY) ; @$(COPY) $< $@

###############################################################################
# Counting the number of lines of code.
###############################################################################

LINES = scripts/ml_lines

.PHONY: lines
lines: $(LINES)
	@echo
	@echo -n 'Metis '
	@$(LINES) $(SRC) src/metis.sml
	@echo

###############################################################################
# Generating the problem sets.
###############################################################################

PROBLEM_DIR = data/problems
TPTP_PROBLEM_DIR = $(HOME)/ptr/tptp/tptp
PROBLEMS2TPTP = bin/mosml/problems2tptp
COPY_PROBLEM = scripts/copy_problem
ALL_SET = $(PROBLEM_DIR)/all
INSTANT_SET = $(PROBLEM_DIR)/instant
NONEQUALITY_SET = $(PROBLEM_DIR)/nonequality
EQUALITY_SET = $(PROBLEM_DIR)/equality
TPTP_SET = $(PROBLEM_DIR)/tptp
HOL_SET = $(PROBLEM_DIR)/hol
BENCHMARK_SET = $(PROBLEM_DIR)/benchmark
MLTON_BENCHMARK_SET = $(PROBLEM_DIR)/mlton-benchmark-20020924
SATISFIABLE_SET = $(PROBLEM_DIR)/satisfiable
TPTP_CNF_SET = $(PROBLEM_DIR)/tptp-cnf
TPTP_FOF_SET = $(PROBLEM_DIR)/tptp-fof

.PHONY: problems-all
problems-all: $(PROBLEMS2TPTP)
	$(PROBLEMS2TPTP) --output-dir $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/BOO/BOO021-1.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/COL/COL058-2.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/COL/COL060-3.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/LCL/LCL009-1.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/LCL/LCL107-1.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/MGT/MGT019+2.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/PUZ/PUZ001-1.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/SWV/SWV010+1.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/SYN/SYN075-1.tptp $(ALL_SET)
	@cp $(TPTP_PROBLEM_DIR)/SYN/SYN075+1.tptp $(ALL_SET)

.PHONY: problems
problems: $(PROBLEMS2TPTP)
	if test -d $(PROBLEM_DIR) ; then rm -r $(PROBLEM_DIR)/ ; fi
	mkdir $(PROBLEM_DIR)
	mkdir $(ALL_SET)
	$(MAKE) problems-all
	mkdir $(NONEQUALITY_SET)
	for p in `$(PROBLEMS2TPTP) --collection nonequality --list` ; do $(COPY_PROBLEM) $(ALL_SET)/$$p.tptp $(NONEQUALITY_SET) ; done
	mkdir $(EQUALITY_SET)
	for p in `$(PROBLEMS2TPTP) --collection equality --list` ; do $(COPY_PROBLEM) $(ALL_SET)/$$p.tptp $(EQUALITY_SET) ; done
	mkdir $(TPTP_SET)
	for p in `$(PROBLEMS2TPTP) --collection tptp --list` ; do $(COPY_PROBLEM) $(ALL_SET)/$$p.tptp $(TPTP_SET) ; done
	mkdir $(HOL_SET)
	for p in `$(PROBLEMS2TPTP) --collection hol --list` ; do $(COPY_PROBLEM) $(ALL_SET)/$$p.tptp $(HOL_SET) ; done
	mkdir $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/TRUE.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/SIMPLE.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/CYCLIC.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/MICHAEL_NORRISH_BUG.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/PROP_6.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/MATHS4_EXAMPLE.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P18.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P39.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P59.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/BAD_CONNECTIONS.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/TRANS_SYMM.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/CYCLIC_SUBSTITUTION_BUG.tptp $(INSTANT_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P48.tptp $(INSTANT_SET)
	mkdir $(BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/LOS.tptp $(BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/STEAM_ROLLER.tptp $(BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/GILMORE_9.tptp $(BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/AGATHA.tptp $(BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/JACOBSON_2.tptp $(BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/WISHNU.tptp $(BENCHMARK_SET)
	mkdir $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P26.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P46.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/GILMORE_1.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/LOS.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/STEAM_ROLLER.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P48.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/P49.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/AGATHA.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/LCL009-1.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/COL060-3.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/COL058-2.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/LCL107-1.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/BOO021-1.tptp $(MLTON_BENCHMARK_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/GRP128-4.003.tptp $(MLTON_BENCHMARK_SET)
	mkdir $(SATISFIABLE_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/LOGICPROOF_1999.tptp $(SATISFIABLE_SET)
	@$(COPY_PROBLEM) $(ALL_SET)/GILMORE_2.tptp $(SATISFIABLE_SET)
	mkdir $(TPTP_CNF_SET)
	@(tptp1T CNF Unsatisfiable || tptp2T -pp Form CNF Status Unsatisfiable) | perl -n -e '$$l = $$_; chomp $$l; if ($$l =~ /^[A-Z]/) { $$l =~ s/[[:space:]].*$$//; $$l =~ s/^([A-Z]*)/\1\/\1/; (system ("$(COPY_PROBLEM) -l $(TPTP_PROBLEM_DIR)/$$l.tptp $(TPTP_CNF_SET)") == 0) or die; }'
	mkdir $(TPTP_FOF_SET)
	@(tptp1T FOF Theorem || tptp2T -pp Form FOF Status Theorem) | perl -n -e '$$l = $$_; chomp $$l; if ($$l =~ /^[A-Z]/) { $$l =~ s/[[:space:]].*$$//; $$l =~ s/^([A-Z]*)/\1\/\1/; (system ("$(COPY_PROBLEM) -l $(TPTP_PROBLEM_DIR)/$$l.tptp $(TPTP_FOF_SET)") == 0) or die; }'

###############################################################################
# Testing Metis on the problem sets.
###############################################################################

TEST_TIME_LIMIT = 60

.PHONY: status-test
status-test: $(METIS)
# Testing basic functionality
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(ALL_SET)/SIMPLE.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(ALL_SET)/REFLEXIVITY.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(ALL_SET)/SYMMETRY.tptp | grep '^SZS status Theorem for'
# Testing the TPTP parser
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/NUMBERED_FORMULAS.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/DEFINED_TERMS.tptp | grep '^SZS status CounterSatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/QUOTED_TERMS.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/QUOTED_TERMS_IDENTITY.tptp | grep '^SZS status Theorem for'
#	Metis wrongly identifies quoted and unquoted special terms
#	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/QUOTED_TERMS_DIFFERENT.tptp | grep '^SZS status CounterSatisfiable for'
#	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/QUOTED_TERMS_SPECIAL.tptp | grep '^SZS status CounterSatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/QUOTED_NUMBERS.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/MIXED_PROBLEM.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) test/tptp/BLOCK_COMMENTS.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) --tptp test/tptp test/tptp/INCLUDE_DIRECTIVE.tptp | grep '^SZS status Theorem for'
# Testing the prover on CASC sample problems
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(ALL_SET)/SYN075-1.tptp | grep '^SZS status Unsatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(ALL_SET)/SYN075+1.tptp | grep '^SZS status Theorem for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(ALL_SET)/MGT019+2.tptp | grep '^SZS status CounterSatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(ALL_SET)/SWV010+1.tptp | grep '^SZS status Satisfiable for'
# Testing the prover on TPTP problems
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/KRS/KRS063+1.tptp | grep '^SZS status Unsatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/KRS/KRS018+1.tptp | grep '^SZS status Satisfiable for'
# Unordered literal selection can't seem to detect this
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/MGT/MGT031-1.tptp | grep '^SZS status Satisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/MGT/MGT041-2.tptp | grep '^SZS status Unsatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/NLP/NLP114-1.tptp | grep '^SZS status Satisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/BOO/BOO003-4.tptp | grep '^SZS status Unsatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/BOO/BOO001-1.tptp | grep '^SZS status Unsatisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/BOO/BOO027-1.tptp | grep '^SZS status Satisfiable for'
# Neither unordered nor positive literal selection can seem to detect this
#	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/BOO/BOO036-1.tptp | grep '^SZS status Satisfiable for'
	@ulimit -t $(TEST_TIME_LIMIT) ; $(METIS) $(TPTP_PROBLEM_DIR)/KRS/KRS174+1.tptp | grep '^SZS status Theorem for'

.PHONY: std-test
std-test: $(METIS)
	ulimit -t $(TEST_TIME_LIMIT) ; find $(NONEQUALITY_SET)/*.tptp | perl -n -e 'system ("time $(METIS) --show all $$_");' 2>&1 | tee std-log
	ulimit -t $(TEST_TIME_LIMIT) ; find $(EQUALITY_SET)/*.tptp | perl -n -e 'system ("time $(METIS) --show all $$_");' 2>&1 | tee -a std-log

.PHONY: tptp-test
tptp-test: $(METIS)
	ulimit -t $(TEST_TIME_LIMIT) ; find $(TPTP_CNF_SET)/*.tptp | perl -n -e 'system ("time $(METIS) --show name --show proof --show saturation $$_");' 2>&1 | tee tptp-log
#	ulimit -t $(TEST_TIME_LIMIT) ; find $(TPTP_FOF_SET)/*.tptp | perl -n -e 'system ("time $(METIS) --show name --show proof --show saturation $$_");' 2>&1 | tee -a tptp-log

.PHONY: tests
tests: status-test std-test tptp-test

###############################################################################
# Profiling using MLton.
###############################################################################

BENCHMARK_OPTS = --show name $(BENCHMARK_SET)/*.tptp

profile-time.mlb: bin/mlton/benchmark.sml
	echo '$$(SML_LIB)/basis/basis.mlb $$(SML_LIB)/basis/mlton.mlb $<' > $@

profile-time: profile-time.mlb
	@echo
	@echo '***************************************************'
	@echo '* Compile the metis benchmark with time profiling *'
	@echo '***************************************************'
	@echo
	$(MLTON) $(MLTON_OPTS) -profile time -profile-stack true -profile-branch true $<
	@echo

profile-time.out profile-time-log: profile-time
	time ./profile-time $(BENCHMARK_OPTS) | tee profile-time-log
	mv mlmon.out profile-time.out

profile-time.txt: profile-time.out Makefile.dev
	mlprof -show-line true -raw true -keep '(and (thresh 0.1) (thresh-stack 0.1))' -split '.*' profile-time profile-time.out > $@

profile-time.dot: profile-time.out Makefile.dev
	mlprof -show-line true -raw true -call-graph $@ -keep '(thresh-stack 1)' -graph-title "Metis Time Profiling" -split '.*' profile-time profile-time.out > /dev/null

.PHONY: profile
profile: profile-time.txt profile-time.dot

###############################################################################
# Releasing.
###############################################################################

RELEASE_DIR = release

HOL_RELEASE_DIR = $(HOME)/dev/metis/hol

RELEASE_STAMP = scripts/release_stamp

EXAMPLE_CNF_PROOF = \
  data/problems/all/SYN075-1.tptp

EXAMPLE_FOF_PROOF = \
  data/problems/all/SYN075+1.tptp

EXAMPLE_FOF_MODEL = \
  data/problems/all/MGT019+2.tptp \
  data/problems/all/SWV010+1.tptp

.PHONY: release-stamp
release-stamp: $(RELEASE_STAMP)
	 $(RELEASE_STAMP) -p Metis doc/*.html src/metis.sml

doc/example-cnf-proof.txt: $(EXAMPLE_CNF_PROOF) $(METIS)
	$(METIS) --show name --show clauses --show proof $(EXAMPLE_CNF_PROOF) > $@

doc/example-fof-proof.txt: $(EXAMPLE_FOF_PROOF) $(METIS)
	$(METIS) --show name --show goal --show clauses --show proof $(EXAMPLE_FOF_PROOF) > $@

doc/example-fof-model.txt: $(EXAMPLE_FOF_MODEL) $(METIS)
	$(METIS) --show name --show goal --show clauses --show saturation $(EXAMPLE_FOF_MODEL) > $@

doc/logical-kernel.txt: src/Thm.sig Makefile.dev
	perl -n -e 'if (defined($$a)) { if ($$_ =~ /Primitive rules of inference/) { $$a = undef; } } elsif ($$_ =~ /Theorem destructors/) { $$a = 0; } if (!defined($$a)) { $$_ =~ s/(Literal|Subst|Term)[.]//g; print STDOUT $$_; }' < $< > $@

.PHONY: documentation
documentation: doc/example-cnf-proof.txt doc/example-fof-proof.txt doc/example-fof-model.txt doc/logical-kernel.txt

.PHONY: tarball
tarball: doc/DONT-RELEASE Makefile.dev
	$(MAKE) clean
	cd .. ; tar cvzhf metis/release/metis.tar.gz --exclude-from metis/doc/DONT-RELEASE metis

.PHONY: release
release: release-stamp mosml mlton polyml status-test documentation
	rm -f $(RELEASE_DIR)/*.html $(RELEASE_DIR)/*.jpg $(RELEASE_DIR)/*.txt
	cp -v doc/*.html doc/*.jpg doc/*.txt $(RELEASE_DIR)/
	cp -v doc/favicon.ico $(METIS) $(RELEASE_DIR)/
	$(MAKE) tarball
	rsync -azv --delete --checksum --size-only --exclude=.gitignore -e ssh $(RELEASE_DIR)/ gilith@login.gilith.com:public_html/software/metis
	ssh gilith@login.gilith.com '/bin/bash -l scripts/install_metis'

.PHONY: hol-release
hol-release: mosml
	scripts/export_hol -d $(HOL_RELEASE_DIR) $(MOSML_OBJ)

###############################################################################
# The build scripts.
###############################################################################

COPY = scripts/copy_src

$(COPY): ../basic/scripts/copy_src
	@cp -fv $< $@
	@chmod -w $@

$(MLPP): ../basic/scripts/mlpp $(COPY) ; @$(COPY) $< $@

$(MOSML_DEP): ../basic/scripts/mosml_dep $(COPY) ; @$(COPY) $< $@

$(LINES): ../basic/scripts/ml_lines $(COPY) ; @$(COPY) $< $@

$(RELEASE_STAMP): ../basic/scripts/release_stamp $(COPY) ; @$(COPY) $< $@

.PHONY: build-scripts
build-scripts: $(COPY) $(MLPP) $(MOSML_DEP) $(LINES) $(RELEASE_STAMP)
