#!/usr/bin/perl

# Copyright (c) 2007 Joe Hurd, All Rights Reserved

use strict;
use warnings;
use Pod::Usage;
use Getopt::Std;

use vars qw($opt_h);

getopts('h');

if ($opt_h or scalar @ARGV != 0)
{
    pod2usage({-exitval => 2,
	       -verbose => 2});
}

# Autoflush STDIN
$|++;

my $state = 'init';

while (my $line = <STDIN>) {
    chomp $line;

    if ($line =~ /^SZS output end CNFRefutation for /) {
        ($state eq 'proof') or die;
        $state = 'end';
        last;
    }

    if ($state eq 'proof') {
        print "$line\n";
    }

    if ($line =~ /^SZS output start CNFRefutation for /) {
        ($state eq 'init') or die;
        $state = 'proof';
    }
}

__END__

=pod

=head1 NAME

extract_proof - separate out proof from an output file

=head1 SYNOPSIS

summarize [-h] < metis-output

=head1 ARGUMENTS

The recognized flags are described below:

=over 2

=item B<-h>

Produce this documentation.

=back

=head1 DESCRIPTION

Extract the first SZS CNFRefutation from an output file.

=head1 BUGS

Waiting to rear their ugly heads.

=head1 AUTHORS

Joe Hurd <joe@gilith.com>

=head1 SEE ALSO

Perl(1).

=cut
